In [1]:
import numpy as np
import tensorflow as tf
import torch

/Users/danialmendigali/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [10]:
x = np.array([25, 2 , 5])
x

array([25,  2,  5])

In [5]:
(25**2 + 2**2 + 5**2) ** (1/2)

25.573423705088842

In [6]:
np.linalg.norm(x)

np.float64(25.573423705088842)

## L2 norm

In [11]:
x

array([25,  2,  5])

In [12]:
(25**2 + 2**2 + 5**2)

654

In [13]:
np.dot(x, x)

np.int64(654)

### max norm

In [14]:
x

array([25,  2,  5])

In [15]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

np.int64(25)