In [37]:
import numpy as np
import tensorflow as tf
import torch

/Users/danialmendigali/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [12]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [3]:
len(x)

3

In [4]:
x.shape

(3,)

In [9]:
type(x)

numpy.ndarray

In [10]:
x[0]

np.float16(25.0)

In [13]:
x_t = x.T
x_t

array([25,  2,  5])

In [14]:
x_t.shape

(3,)

In [15]:
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [16]:
y.shape

(1, 3)

In [17]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [18]:
y_t.shape

(3, 1)

In [20]:
y_t.T

array([[25,  2,  5]])

In [21]:
y_t.T.shape

(1, 3)

In [23]:
z = np.zeros(3) # zero vectors 
z

array([0., 0., 0.])

In [32]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [30]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [38]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>