In [1]:
import numpy as np
import tensorflow as tf
import torch

/Users/danialmendigali/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
x = np.array([[25, 2], [5, 26], [3, 7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
x.shape

(3, 2)

In [5]:
x.size

6

In [6]:
x[:, 0]

array([25,  5,  3])

In [7]:
x[1, :]

array([ 5, 26])

In [8]:
x[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

In [11]:
x_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
x_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [12]:
x_pt.shape

torch.Size([3, 2])

In [13]:
x_pt[1,:]

tensor([ 5, 26])

In [17]:
x_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [18]:
tf.rank(x_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [19]:
tf.shape(x_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [20]:
x_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>