In [2]:
import numpy as np
import tensorflow as tf
import torch

In [3]:
x = np.array([[4, 2], [-5, -3]])
Xinv = np.linalg.inv(x)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [4]:
y = np.array([4, -7])
y

array([ 4, -7])

In [5]:
w = np.dot(Xinv, y)
w

array([-1.,  4.])

In [6]:
np.dot(x, w)

array([ 4., -7.])

### In PyTorch and TensorFlow

In [12]:
torch.inverse(torch.tensor([[4, 2], [-5, -3.]]))

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]])

In [11]:
tf.linalg.inv(tf.Variable([[4, 2], [-5, -3.]]))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4999998,  0.9999998],
       [-2.4999995, -1.9999996]], dtype=float32)>

In [13]:
a = np.array([[-4, 1], [-8, 2]])
a

array([[-4,  1],
       [-8,  2]])

In [14]:
ainv = np.linalg.inv(a)

LinAlgError: Singular matrix