In [1]:
import pandas as pd 
import numpy as np 
import scipy
import matplotlib.pyplot as plt 
import seaborn as sns

from sklearn.cluster import KMeans

pd.options.display.float_format = '{:20.2f}'.format

pd.set_option('display.max_columns', 999)

In [6]:
Q1 = np.array([ [1, -1], [1, 1]]) / np.sqrt(2)
Q2 = np.array([ [1, 2, 2], [2, 1, -2], [-2, 2, -1]]) / 3


print(Q1)
print(Q2)

print(Q1.T @ Q1)
print(Q2.T @ Q2)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[[ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]
 [-0.66666667  0.66666667 -0.33333333]]
[[1.00000000e+00 2.23711432e-17]
 [2.23711432e-17 1.00000000e+00]]
[[1.00000000e+00 2.77555756e-17 0.00000000e+00]
 [2.77555756e-17 1.00000000e+00 1.23358114e-17]
 [0.00000000e+00 1.23358114e-17 1.00000000e+00]]


In [10]:
print(Q1 @ Q1.T)
print(Q1.T @ Q1)


print(Q2 @ Q2.T)
print(Q2.T @ Q2)

[[1. 0.]
 [0. 1.]]
[[1.00000000e+00 2.23711432e-17]
 [2.23711432e-17 1.00000000e+00]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1.00000000e+00 2.77555756e-17 0.00000000e+00]
 [2.77555756e-17 1.00000000e+00 1.23358114e-17]
 [0.00000000e+00 1.23358114e-17 1.00000000e+00]]
