In [5]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

from sklearn.cluster import KMeans

pd.options.display.float_format = '{:20.2f}'.format

pd.set_option('display.max_columns', 999)

In [7]:
A = np.arange(60).reshape(6, 10)
sub = A[1:3:1, 0:5:1]
sub

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [8]:
Mrows = 4
Ncols = 6
A = np.random.randn(Mrows, Ncols)

In [10]:
A = np.array([ [4, 5, 1], [0, 1, 11], [4, 9, 7]])
S = 6
A + S * np.eye(len(A))

array([[10.,  5.,  1.],
       [ 0.,  7., 11.],
       [ 4.,  9., 13.]])

In [14]:
A = np.random.randn(3, 4)
B = np.random.randn(3, 4)

A * B

array([[ 0.46758868, -1.04219208,  0.04005236,  0.31578599],
       [-1.06945838,  0.25911601, -0.38649343,  0.84375274],
       [-0.34798146,  0.49426458, -1.23179752,  0.57601178]])

In [16]:
M = np.array([[2 ,3], [2, 1]])
x = np.array([[1, 1.5]]).T

Mx = M@x
Mx

array([[6.5],
       [3.5]])

In [21]:
A = np.array([[3, 4, 5], [1, 2, 3]])
A_T1 = A.T
A_T2 = np.transpose(A)
A_T1, A_T2

(array([[3, 1],
        [4, 2],
        [5, 3]]),
 array([[3, 1],
        [4, 2],
        [5, 3]]))