In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt 
import torch

/Users/danialmendigali/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
a = np.array([[4, 2], [-5, -3]])
a

array([[ 4,  2],
       [-5, -3]])

In [3]:
lambdas, v = np.linalg.eig(a)

In [4]:
v

array([[ 0.70710678, -0.37139068],
       [-0.70710678,  0.92847669]])

In [7]:
Vinv = np.linalg.inv(v)
Vinv

array([[2.3570226 , 0.94280904],
       [1.79505494, 1.79505494]])

In [8]:
Lambda = np.diag(lambdas)
Lambda

array([[ 2.,  0.],
       [ 0., -1.]])

In [9]:
np.dot(v, np.dot(Lambda, Vinv))

array([[ 4.,  2.],
       [-5., -3.]])

In [10]:
a = np.array([[2, 1], [1, 2]])
a

array([[2, 1],
       [1, 2]])

In [12]:
lambdas, q = np.linalg.eig(a)
lambdas

array([3., 1.])

In [14]:
Lambda = np.diag(lambdas)
Lambda

array([[3., 0.],
       [0., 1.]])

In [16]:
q

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [19]:
np.dot(q, np.dot(Lambda, q.T))

array([[2., 1.],
       [1., 2.]])

In [20]:
np.dot(q.T, q)

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])

In [21]:
np.dot(q, q.T)

array([[ 1.00000000e+00, -2.23711432e-17],
       [-2.23711432e-17,  1.00000000e+00]])